# Generated by Django 4.2.1 on 2023-05-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Admin hasan', max_length=100),
            preserve_default=False,
        ),
    ]
