# Generated by Django 4.2.1 on 2023-05-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
